import React, { useMemo, useState } from 'react';
import { CreditCard, AlertCircle, Receipt, Search, Printer, Phone, CheckCircle2, Wallet, X, Trash2, BarChart3 } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { FeePayment, Student } from '../types';

const MONTHS = ['April','May','June','July','August','September','October','November','December','January','February','March'];
const getStartYear = (academicYear: string) => { const m = academicYear.match(/20\d{2}/); return m ? Number(m[0]) : new Date().getFullYear(); };
const monthYear = (month: string, startYear: number) => `${month} ${MONTHS.indexOf(month) < 9 ? startYear : startYear + 1}`;
const netMonthlyFee = (s: Student) => Math.max(0,(s.monthlyTuitionFee||0)+(s.monthlyFoodFee||0)+(s.monthlyTransportFee||0)-(s.feeDiscount||0));

export const FeesManagement: React.FC = () => {
  const { students, payments, settings, activeSubTab, setActiveSubTab, setIsQuickPaymentModalOpen, setActivePaymentForReceipt, showToast, deletePayment } = useApp();
  const startYear = getStartYear(settings.academicYear);
  const currentTab = activeSubTab || 'register';
  const [selectedMonth,setSelectedMonth] = useState(MONTHS[Math.max(0,new Date().getMonth()-3)] || 'April');
  const [selectedDept,setSelectedDept] = useState('all');
  const [searchQuery,setSearchQuery] = useState('');
  const [selectedPayment,setSelectedPayment] = useState<FeePayment|null>(null);

  const activeStudents = useMemo(() => students.filter(s=>s.status==='active'),[students]);
  const visibleStudents = useMemo(() => { const q=searchQuery.trim().toLowerCase(); return activeStudents.filter(s => { const hay=[s.fullName,s.banglaName,s.rollNo,s.guardianName,s.guardianPhone,s.address].join(' ').toLowerCase(); return (!q||hay.includes(q))&&(selectedDept==='all'||s.department===selectedDept); }); },[activeStudents,searchQuery,selectedDept]);
  const getPaid = (studentId:string,month:string) => payments.filter(p=>p.studentId===studentId&&p.month.includes(monthYear(month,startYear))).reduce((sum,p)=>sum+Number(p.paidAmount||0),0);
  const getBilled = (s:Student) => netMonthlyFee(s);

  const selectedStats = useMemo(()=>{ const rows=activeStudents.map(s=>{const billed=getBilled(s),paid=getPaid(s.id,selectedMonth);return {billed,paid,due:Math.max(0,billed-paid)}}); return { billed:rows.reduce((a,r)=>a+r.billed,0),paid:rows.reduce((a,r)=>a+r.paid,0),due:rows.reduce((a,r)=>a+r.due,0),paidStudents:rows.filter(r=>r.billed>0&&r.paid>=r.billed).length,partialStudents:rows.filter(r=>r.paid>0&&r.paid<r.billed).length,dueStudents:rows.filter(r=>r.billed>0&&r.paid===0).length,freeStudents:rows.filter(r=>r.billed===0).length }; },[activeStudents,selectedMonth,payments,startYear]);
  const academicStats = useMemo(()=>{ const billed=activeStudents.reduce((a,s)=>a+getBilled(s)*12,0); const paid=payments.reduce((a,p)=>a+Number(p.paidAmount||0),0); return {billed,paid,due:Math.max(0,billed-paid)}; },[activeStudents,payments]);
  const monthSummary = useMemo(()=>MONTHS.map(month=>{const billed=activeStudents.reduce((a,s)=>a+getBilled(s),0);const paid=activeStudents.reduce((a,s)=>a+getPaid(s.id,month),0);return {month,billed,paid,due:Math.max(0,billed-paid)};}),[activeStudents,payments,startYear]);
  const filteredPayments = useMemo(()=>{const q=searchQuery.trim().toLowerCase();return payments.filter(p=>{const hay=[p.studentName,p.studentBanglaName,p.rollNo,p.receiptNo].join(' ').toLowerCase();return (!q||hay.includes(q))&&(selectedMonth==='all'||p.month.includes(monthYear(selectedMonth,startYear)))&&(selectedDept==='all'||p.department===selectedDept);});},[payments,searchQuery,selectedMonth,selectedDept,startYear]);
  const dueRows = useMemo(()=>visibleStudents.map(s=>{const billed=getBilled(s),paid=getPaid(s.id,selectedMonth);return {student:s,billed,paid,due:Math.max(0,billed-paid)};}).filter(r=>r.due>0),[visibleStudents,selectedMonth,payments,startYear]);

  const sendReminder = async (student:Student,due:number) => { const text=`আসসালামু আলাইকুম। ${student.fullName} (রোল ${student.rollNo})-এর ${monthYear(selectedMonth,startYear)} মাসের বকেয়া ফি ${settings.currencySymbol}${due.toLocaleString()}। অনুগ্রহ করে ফি পরিশোধ করুন। - ${settings.banglaName}`; try { await navigator.clipboard.writeText(text); showToast('Due reminder message copied.','info'); } catch { showToast(text,'info'); } };

  return <div id="fees-management-view" className="space-y-5 pb-12">
    <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div><h2 className="text-xl sm:text-2xl font-extrabold text-slate-900 flex items-center gap-2"><CreditCard className="w-6 h-6 text-emerald-700"/> ফি ও বেতন ব্যবস্থাপনা</h2><p className="text-xs sm:text-sm text-slate-500 mt-1">{settings.academicYear} • April → March • Paid / Partial / Due / ATIM</p></div><div className="flex gap-2"><button onClick={()=>window.print()} className="inline-flex items-center gap-2 px-3 py-2.5 rounded-xl border bg-white text-xs font-bold"><Printer className="w-4 h-4"/> Print</button><button onClick={()=>setIsQuickPaymentModalOpen(true)} className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-emerald-700 text-white text-xs sm:text-sm font-bold"><Receipt className="w-4 h-4"/> নতুন ফি গ্রহণ</button></div></div>

    <div className="grid grid-cols-2 lg:grid-cols-6 gap-3"><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] text-slate-500">Active Students</p><p className="text-2xl font-black">{activeStudents.length}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] text-slate-500">{selectedMonth} Bill</p><p className="text-xl font-black">{settings.currencySymbol}{selectedStats.billed.toLocaleString()}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] text-slate-500">এই মাসে জমা</p><p className="text-xl font-black text-emerald-700">{settings.currencySymbol}{selectedStats.paid.toLocaleString()}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] text-slate-500">এই মাসে বাকি</p><p className="text-xl font-black text-rose-700">{settings.currencySymbol}{selectedStats.due.toLocaleString()}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] text-slate-500">Academic Collection</p><p className="text-xl font-black text-emerald-700">{settings.currencySymbol}{academicStats.paid.toLocaleString()}</p></div><div className="bg-white border rounded-2xl p-4"><p className="text-[10px] text-slate-500">Academic Due</p><p className="text-xl font-black text-amber-700">{settings.currencySymbol}{academicStats.due.toLocaleString()}</p></div></div>

    <div className="bg-white border rounded-2xl p-4 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="relative"><Search className="w-4 h-4 text-slate-400 absolute left-3 top-1/2 -translate-y-1/2"/><input value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} placeholder="নাম, রোল, ফোন বা রসিদ খুঁজুন..." className="w-full pl-9 pr-3 py-2.5 rounded-xl bg-slate-50 border text-xs sm:text-sm"/></div><select value={selectedMonth} onChange={e=>setSelectedMonth(e.target.value)} className="px-3 py-2.5 rounded-xl bg-slate-50 border text-xs sm:text-sm">{MONTHS.map(m=><option key={m} value={m}>{monthYear(m,startYear)}</option>)}<option value="all">All Months</option></select><select value={selectedDept} onChange={e=>setSelectedDept(e.target.value)} className="px-3 py-2.5 rounded-xl bg-slate-50 border text-xs sm:text-sm"><option value="all">সকল Class / বিভাগ</option><option value="hafizia">HIFZ</option><option value="nazera">NAZERA</option><option value="noorani">NOORANI</option><option value="kitab">KITAB</option></select></div><div className="flex flex-wrap gap-2">{[['register','মাসিক Fee Register'],['payment','Payment Records'],['due','Due Management'],['receipt','Receipts'],['summary','Monthly Summary']].map(([key,label])=><button key={key} onClick={()=>setActiveSubTab(key)} className={`px-3 py-2 rounded-xl text-xs font-bold ${currentTab===key?'bg-emerald-700 text-white':'bg-slate-100 text-slate-600'}`}>{label}</button>)}</div></div>

    {currentTab==='register' && <div className="bg-white rounded-2xl border overflow-hidden shadow-sm"><div className="p-4 border-b flex items-center justify-between"><div><h3 className="font-extrabold">MONTHLY FEE REGISTER</h3><p className="text-[11px] text-slate-500">{settings.academicYear} • {visibleStudents.length} students</p></div><Wallet className="w-5 h-5 text-emerald-700"/></div><div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-xs"><thead className="bg-slate-900 text-white"><tr><th className="px-3 py-3 text-left sticky left-0 bg-slate-900">ROLL</th><th className="px-3 py-3 text-left sticky left-[70px] bg-slate-900">STUDENTS</th>{MONTHS.map(m=><th key={m} className="px-2 py-3 text-center">{m.slice(0,3).toUpperCase()}<div className="text-[9px] opacity-70">{MONTHS.indexOf(m)<9?startYear:startYear+1}</div></th>)}<th className="px-3 py-3 text-right">MONTHLY</th></tr></thead><tbody className="divide-y">{visibleStudents.map(s=><tr key={s.id} className="hover:bg-emerald-50/30"><td className="px-3 py-2 font-mono font-bold sticky left-0 bg-white">{s.rollNo}</td><td className="px-3 py-2 font-bold sticky left-[70px] bg-white"><div>{s.fullName}</div><div className="text-[10px] text-slate-400">{s.guardianName}</div></td>{MONTHS.map(month=>{const fee=getBilled(s),paid=getPaid(s.id,month);const label=fee===0?'ATIM':paid>=fee?'✓ paid':paid>0?`${settings.currencySymbol}${paid.toLocaleString()}`:'-';const cls=fee===0?'bg-sky-100 text-sky-700':paid>=fee?'bg-emerald-100 text-emerald-800':paid>0?'bg-amber-100 text-amber-800':'bg-rose-50 text-rose-700';return <td key={month} className="px-1.5 py-2 text-center"><span className={`inline-flex min-w-[50px] justify-center px-1.5 py-1 rounded-md text-[10px] font-bold ${cls}`}>{label}</span></td>;})}<td className="px-3 py-2 text-right font-extrabold">{getBilled(s)===0?<span className="text-sky-600">ATIM</span>:`${settings.currencySymbol}${getBilled(s).toLocaleString()}`}</td></tr>)}</tbody><tfoot className="bg-emerald-950 text-white font-bold"><tr><td className="px-3 py-3" colSpan={2}>TOTAL — {activeStudents.length} ACTIVE</td>{MONTHS.map(m=>{const row=monthSummary.find(x=>x.month===m)!;return <td key={m} className="px-2 py-3 text-center">{settings.currencySymbol}{row.paid.toLocaleString()}</td>})}<td className="px-3 py-3 text-right">{settings.currencySymbol}{selectedStats.paid.toLocaleString()}</td></tr></tfoot></table></div></div>}

    {currentTab==='summary' && <div className="bg-white rounded-2xl border overflow-hidden shadow-sm"><div className="p-4 border-b"><h3 className="font-extrabold flex items-center gap-2"><BarChart3 className="w-5 h-5 text-emerald-700"/> MONTHLY COLLECTION SUMMARY</h3></div><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-900 text-white"><tr><th className="px-4 py-3 text-left">MONTH</th><th className="px-4 py-3 text-right">TOTAL BILL</th><th className="px-4 py-3 text-right">COLLECTED</th><th className="px-4 py-3 text-right">DUE</th></tr></thead><tbody>{monthSummary.map(r=><tr key={r.month} className="border-b"><td className="px-4 py-3 font-bold">{monthYear(r.month,startYear)}</td><td className="px-4 py-3 text-right">{settings.currencySymbol}{r.billed.toLocaleString()}</td><td className="px-4 py-3 text-right font-bold text-emerald-700">{settings.currencySymbol}{r.paid.toLocaleString()}</td><td className="px-4 py-3 text-right font-bold text-rose-700">{settings.currencySymbol}{r.due.toLocaleString()}</td></tr>)}</tbody><tfoot className="bg-slate-100 font-extrabold"><tr><td className="px-4 py-3">TOTAL</td><td className="px-4 py-3 text-right">{settings.currencySymbol}{academicStats.billed.toLocaleString()}</td><td className="px-4 py-3 text-right text-emerald-700">{settings.currencySymbol}{academicStats.paid.toLocaleString()}</td><td className="px-4 py-3 text-right text-rose-700">{settings.currencySymbol}{academicStats.due.toLocaleString()}</td></tr></tfoot></table></div></div>}

    {currentTab==='due' && <div className="bg-white rounded-2xl border overflow-hidden shadow-sm"><div className="p-4 border-b flex items-center justify-between"><div><h3 className="font-extrabold">DUE STUDENTS — {monthYear(selectedMonth,startYear)}</h3><p className="text-[11px] text-slate-500">Partial payment-ও এখানে দেখা যাবে</p></div><AlertCircle className="w-5 h-5 text-amber-600"/></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead className="bg-slate-50"><tr><th className="px-4 py-3 text-left">ROLL</th><th className="px-4 py-3 text-left">STUDENT</th><th className="px-4 py-3 text-left">PHONE</th><th className="px-4 py-3 text-right">MONTHLY BILL</th><th className="px-4 py-3 text-right">PAID</th><th className="px-4 py-3 text-right">DUE</th><th className="px-4 py-3">ACTION</th></tr></thead><tbody className="divide-y">{dueRows.map(r=><tr key={r.student.id}><td className="px-4 py-3 font-bold">{r.student.rollNo}</td><td className="px-4 py-3"><div className="font-bold">{r.student.fullName}</div><div className="text-[10px] text-slate-400">{r.student.guardianName}</div></td><td className="px-4 py-3 font-mono">{r.student.guardianPhone||'—'}</td><td className="px-4 py-3 text-right">{settings.currencySymbol}{r.billed.toLocaleString()}</td><td className="px-4 py-3 text-right text-emerald-700 font-bold">{settings.currencySymbol}{r.paid.toLocaleString()}</td><td className="px-4 py-3 text-right text-rose-700 font-extrabold">{settings.currencySymbol}{r.due.toLocaleString()}</td><td className="px-4 py-3"><div className="flex justify-center gap-1"><button onClick={()=>setIsQuickPaymentModalOpen(true)} className="px-2.5 py-1.5 rounded-lg bg-emerald-700 text-white text-[10px] font-bold">Collect</button><button onClick={()=>sendReminder(r.student,r.due)} className="p-1.5 rounded-lg bg-slate-100 text-slate-600"><Phone className="w-3.5 h-3.5"/></button></div></td></tr>)}{dueRows.length===0&&<tr><td colSpan={7} className="py-12 text-center text-slate-400"><CheckCircle2 className="w-8 h-8 mx-auto mb-2 text-emerald-500"/>এই মাসে কোনো Due নেই</td></tr>}</tbody></table></div></div>}

    {currentTab==='payment' && <div className="bg-white rounded-2xl border overflow-hidden shadow-sm"><div className="p-4 border-b"><h3 className="font-extrabold">PAYMENT RECORDS</h3><p className="text-[11px] text-slate-500">{filteredPayments.length}টি payment record</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-xs"><thead className="bg-slate-900 text-white"><tr><th className="px-3 py-3 text-left">RECEIPT</th><th className="px-3 py-3 text-left">STUDENT</th><th className="px-3 py-3">MONTH</th><th className="px-3 py-3 text-right">BILL</th><th className="px-3 py-3 text-right">PAID</th><th className="px-3 py-3 text-right">DUE</th><th className="px-3 py-3">DATE</th><th className="px-3 py-3">ACTION</th></tr></thead><tbody className="divide-y">{filteredPayments.map(p=><tr key={p.id} className="hover:bg-slate-50"><td className="px-3 py-3 font-mono font-bold text-emerald-700">{p.receiptNo}</td><td className="px-3 py-3"><b>{p.studentName}</b><div className="text-[10px] text-slate-400">Roll {p.rollNo}</div></td><td className="px-3 py-3 text-center">{p.month}</td><td className="px-3 py-3 text-right">{settings.currencySymbol}{Number(p.totalPayable||p.subtotal||0).toLocaleString()}</td><td className="px-3 py-3 text-right font-bold text-emerald-700">{settings.currencySymbol}{Number(p.paidAmount||0).toLocaleString()}</td><td className="px-3 py-3 text-right font-bold text-rose-700">{settings.currencySymbol}{Number(p.dueRemaining||0).toLocaleString()}</td><td className="px-3 py-3 text-center">{p.paymentDate}</td><td className="px-3 py-3"><div className="flex justify-center gap-1"><button onClick={()=>setActivePaymentForReceipt(p)} className="p-1.5 rounded-lg bg-emerald-50 text-emerald-700"><Printer className="w-3.5 h-3.5"/></button><button onClick={()=>setSelectedPayment(p)} className="p-1.5 rounded-lg bg-slate-100 text-slate-600"><CreditCard className="w-3.5 h-3.5"/></button></div></td></tr>)}{filteredPayments.length===0&&<tr><td colSpan={8} className="py-12 text-center text-slate-400">কোনো payment record পাওয়া যায়নি</td></tr>}</tbody></table></div></div>}

    {currentTab==='receipt' && <div className="bg-white rounded-2xl border overflow-hidden shadow-sm"><div className="p-4 border-b"><h3 className="font-extrabold">MONEY RECEIPTS</h3><p className="text-[11px] text-slate-500">Receipt view / print</p></div><div className="divide-y">{filteredPayments.slice(0,50).map(p=><div key={p.id} className="p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><p className="font-extrabold text-emerald-800">{p.receiptNo}</p><p className="text-sm font-bold">{p.studentName} • Roll {p.rollNo}</p><p className="text-xs text-slate-500">{p.month} • {p.paymentDate} • Paid {settings.currencySymbol}{Number(p.paidAmount||0).toLocaleString()}</p></div><button onClick={()=>setActivePaymentForReceipt(p)} className="inline-flex items-center justify-center gap-2 px-3 py-2 rounded-xl bg-emerald-700 text-white text-xs font-bold"><Printer className="w-4 h-4"/> View / Print</button></div>)}{filteredPayments.length===0&&<div className="p-12 text-center text-slate-400">কোনো receipt নেই</div>}</div></div>}

    {selectedPayment && <div className="fixed inset-0 z-50 bg-slate-950/60 flex items-center justify-center p-4"><div className="bg-white rounded-3xl w-full max-w-md p-5 shadow-2xl"><div className="flex items-center justify-between mb-4"><h3 className="font-extrabold">Payment Details</h3><button onClick={()=>setSelectedPayment(null)}><X className="w-5 h-5"/></button></div><div className="space-y-2 text-sm"><p><b>Receipt:</b> {selectedPayment.receiptNo}</p><p><b>Student:</b> {selectedPayment.studentName}</p><p><b>Month:</b> {selectedPayment.month}</p><p><b>Bill:</b> {settings.currencySymbol}{Number(selectedPayment.totalPayable||selectedPayment.subtotal||0).toLocaleString()}</p><p><b>Paid:</b> {settings.currencySymbol}{Number(selectedPayment.paidAmount||0).toLocaleString()}</p><p><b>Due:</b> {settings.currencySymbol}{Number(selectedPayment.dueRemaining||0).toLocaleString()}</p><p><b>Method:</b> {selectedPayment.paymentMethod}</p><p><b>Received By:</b> {selectedPayment.receivedBy}</p></div><div className="mt-5 flex gap-2"><button onClick={()=>setActivePaymentForReceipt(selectedPayment)} className="flex-1 py-2.5 rounded-xl bg-emerald-700 text-white text-xs font-bold"><Printer className="w-4 h-4 inline mr-1"/> Receipt</button><button onClick={()=>{if(confirm('Delete this payment receipt?')){deletePayment(selectedPayment.id);setSelectedPayment(null);}}} className="py-2.5 px-3 rounded-xl bg-rose-50 text-rose-700"><Trash2 className="w-4 h-4"/></button></div></div></div>}
  </div>;
};
